# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/user_unknown.png', null=True, upload_to='avatars'),
        ),
    ]
