# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 17:13
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171206_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/user_unknown.png', null=True, upload_to=core.models.upload_to),
        ),
    ]
